steps:
  # 1. Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/${_AR_PROJECT_ID}/${_AR_REPOSITORY}/${_SERVICE_NAME}:$TAG_NAME', '.']
  
  # 2. Push the image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/${_AR_PROJECT_ID}/${_AR_REPOSITORY}/${_SERVICE_NAME}:$TAG_NAME']
  
  # 3. Update Cloud Run service
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'services'
      - 'update'
      - '${_SERVICE_NAME}'
      - '--image'
      - 'us-central1-docker.pkg.dev/${_AR_PROJECT_ID}/${_AR_REPOSITORY}/${_SERVICE_NAME}:$TAG_NAME'
      - '--region'
      - '${_DEPLOY_REGION}'

# ADD THIS SECTION BELOW
options:
  logging: CLOUD_LOGGING_ONLY

substitutions:
    _AR_PROJECT_ID: elevated-codex-295919
    _AR_REPOSITORY: cloud-run-source-deploy
    _SERVICE_NAME: petdigitwin
    _DEPLOY_REGION: us-central1
